project:
  type: website

website:
  title: "Moral Reasoning Across Disciplines"
  navbar:
    left:
      - text: "Home" 
        file: index.qmd
      - text: "Agendas & Readings"
        file: 'readings/readings_agendas.qmd'
      - text: "About" 
        menu:
          - text: "Goals & Commitments"
            file: about.qmd
          - people.qmd
    tools:
      - icon: github
        menu:
        - text: Website Source Code 
          url:  https://github.com/mswick29/mrad-website
  sidebar:
  - title: "Overview"
    style: "docked"
    contents:
      - 'readings/readings_agendas.qmd'
      - 'readings/week1/202401_reading_MS.qmd'
format:
  html:
    theme: solar
    css: styles.css
    toc: true



