---
title: "Commitments: Now & Looking Forward"
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    sidebar: false
---

## Vision Statement
I want to create a space for researchers and applied practitioners to exchange ideas related to moral reasoning and development, engage in methodological creativity, and seek impact in their work. This requires heavy communication, relationship building, and openness to new ideas outside of our own disciplines and work. Ultimately, this would culminate in its own research society dedicated to the study of morality and moral development. The society would be comprised of a wide range of disciplines, with separate discipline branches as needed.

## Mission Statement
Current expectations are to first, build a small UCD community of graduate students who are interested in moral reasoning, fairness, justice, and other related concepts in their research. This would begin with an initial exchange of ideas (e.g., a reading group) and snowball into other activities such as community engagement, presentation of research, and collaboration. The more people the better, and so we want to set-up this reading group for long-term success in a sustainable way. Eventual governance positions will be set into place.

## Commitment to Equity, Diversity, & Inclusion
Justice and fairness is inseparable from discussions surrounding morality, moral reasoning, and moral development. Any endeavor in creating an inclusive, interdisciplinary group dedicated to the study of morality, fairness, and justice must consider systemic racism and the oppression of systematically disadvantaged populations in our society.
