---
title: "Morality, Fairness, & Justice Across Disciplines"
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    sidebar: false
---

# ☀️ Welcome!

Thank you for hopping on this site! This will be the landing page for our meetings. Look around and you'll find:

1. Meeting Schedule
2. Discussion Guidelines
3. Agendas & Readings
4. Goals of the Reading Group
5. People of the Group

# 📅 WQ 2024 Schedule

| Date           | Topic        | Leader  | Reading  |
|----------------|--------------|---------|----------|
| Tues., Jan. 16 | Introduction | Maia S. | *None*   |
| Tues., Jan. 30 | *TBD*        | *TBD*   | *TBD *   |
| Tues., Feb. 13 | *TBD*        | *TBD*   | *TBD *   |
| Tues., Feb. 27 | *TBD*        | *TBD*   | *TBD *   |
| Tues., Mar. 12 | *TBD*        | *TBD*   | *TBD *   |
| Tues., Mar. 26 | ***Spring Break!***        | ***None***| ***None** |
: {.striped .hover tbl-colwidths="[11,49,20,20]"}

# 📑 Discussion Guidelines

::: panel-tabset
## Participant

### Being Open to Learning

-   What do you hope to learn from the discussion leader's field?

### Showing Up With Your Perspective

-   How can your expertise further inform, build on, or learn from the work presented today?

### Sharing Resources

-   After reading the work, did it remind you of anything you've read or seen previously? If so, please be prepared to share with the discussion leader and/or group.

## Discussion Lead

### Choosing a Paper
Below are a few guiding questions for choosing a work to share with the group. 

-   What is a written work that ignited your passion for pursuing a graduate degree in your field?
-   What is a written work that is representative of your research interests?
-   What is a written work from your discipline that you think everyone should read?
-   What is a written work that either challenged your perspective or someone elses that you think everyone should read?

### Crafting Discussion Questions

-   Do you want readers to be primed with any information or set with a certain mindset before reading the work?
-   What are the key takeaways you want readers to have after reading?
-   What excited you (or did not excite you) about this work? How can you communicate that to others?
-   How does your research expand the field, especially in light of the paper we read?

### Logistics
-   Please share your a .pdf of your written work with the group. We will upload a copy into the relevant agenda page on the site and/or share in an email thread.
-   Please share any discussion questions too.
-   If there are any good summary quotes from the text, please share them too! We will add them to the agenda.
:::
